### ISSUE TITLE
TODO md

### ISSUE THREAD

**Issue by Malachov** [Malachov/predictit#1]
:sparkles: **Feel free to add any your wishes** :sparkles:

- [ ] Remove main_function.py - main.py for multiple output
- [ ] Nem models - HONU, LebenvergMarquardt
- [ ] New criterion model - with lagged values / autocorrelation for anomaly prediction
- [ ] Dask for big data
- [ ] PCA on higher dimension data?
- [ ] Data smoothing as a parametr
- [ ] Manage automation on columns
- [ ] [Archive a card](https://help.github.com/articlesData as function input - not only CSV and database
- [ ] Numba optimization or PyPy - how to install libraries
- [ ] Ensure for appropriate dtype in calculations (64? best)
- [] Check dtypes
